### ISSUE TITLE
[Scorcher] Heavy GFX problem in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#475]
Yaba Sanshiro 1.2.2

![1scorcher](https://user-images.githubusercontent.com/12481242/34339791-26966de8-e979-11e7-92d0-3753f2bf4c08.JPG)

**Comment by BenjaminSiskoo** [comment]
Menu is not displayed with Yaba Sanshiro 1.3.0 RC but some progress in game.

![1scorcher](https://user-images.githubusercontent.com/12481242/34650459-9edb3730-f3b9-11e7-9b5f-4b22127b9526.JPG)
![1scorcheringame](https://user-images.githubusercontent.com/12481242/34650460-9efa3342-f3b9-11e7-808c-7a97c76e0907.JPG)

**Comment by devmiyax** [comment]
it seems nice.

![image](https://user-images.githubusercontent.com/1174152/35019457-512bcf96-fb6a-11e7-9fd8-2a378eaaeca5.png)

**Comment by BenjaminSiskoo** [comment]
Tested with Yaba Sanshiro 1.3.0 RC and another ISO few minutes ago, same problem with the windows port.

**Comment by devmiyax** [comment]
I'm testing "Yaba Sanshiro 1.3.0"

**Comment by BenjaminSiskoo** [comment]
Yaba Sanshiro 1.30 RC 01.17.2018 (Windows port) : 

Menu is fixed. In Game, GFX problem with the background. 

![1scorcher](https://user-images.githubusercontent.com/12481242/35040333-9bacf5dc-fb78-11e7-9a49-3ec063b15dfe.JPG)

**Comment by FCare** [comment]
It seems the GFX issue is still present but you need to start Scorcher as the first game. If you launch an other game (like BlamMachineHeead) and then launch Scorcher without rebooting the application, all is fine. But if scorcher is the first game, then you have an issue...
